CREATE TABLE Games(
	Id INTEGER PRIMARY KEY NOT NULL,
	RadiantVictory INTEGER NOT NULL,
	GameMode TEXT
);

CREATE TABLE Heroes(
	Id INTEGER PRIMARY KEY NOT NULL,
	Name TEXT NOT NULL
);

CREATE TABLE PicksBans(
	Team INTEGER NOT NULL,	
	IsPick INTEGER NOT NULL,
	PickOrder INTEGER NOT NULL,
	GameId INTEGER NOT NULL,
	HeroId INTEGER NOT NULL,
	FOREIGN KEY(GameId) REFERENCES Games(Id),
	FOREIGN KEY(HeroId) REFERENCES Heroes(Id)
);